### ISSUE TITLE
Fix problems related to Filament picking

### ISSUE THREAD

**Issue by grassydragon** [SceneView/sceneview-android#91]
All problems related to Filament picking should be fixed including:

- [x] Finding a `Node` that was touched from a renderable ID #96
- [x] Returning a picked renderable ID together with a `Node` #96
- [x] Calling event listeners on the `SceneView` and `Node`s #96
- [x] Removing redundant methods and adding documentation #96
- [x] Moving a `Node` #99 
- [x] Enabling scale, rotate and move transformations at the same time #113
- [x] Correctly showing the selection visualizer under a `Node` 66b5bf5114afe23c32c88fbc615ef91795d89ed6

**Comment by grassydragon** [comment]
Implementing `ViewNode` picking isn't as simple as picking other objects using Filament since transparent renderables don't participate in picking (https://github.com/google/filament/discussions/5851). This feature should be supported inside SceneView or Filament.
